spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379

server:
  port: 8082

datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  driver-class-name: "org.postgresql.Driver"
  username: postgres
  password: postgres

integration:
  currency-property:
    base-url: https://api.currencyapi.com
    latest: v3/latest
    headers:
      - key: apiKey
        value: cur_live_XFxg7WWL0eiU53NAr4Ze7WhkoxdOs3Kc9z5lWUne

logging:
  level:
    org:
      springframework:
        security: DEBUG